### ISSUE TITLE
flask not launching

### ISSUE THREAD

**Issue by JmiXIII** [stefanhoelzl/vue.py#27] opened 2021-11-18 10:27 UTC
Installation
```
pip install vuepy
pip install vuepy[flask]
mkdir vuepy
cd vuepy
```

App.py :
```

from vue import *

class App(VueComponent):
    template = "<div>Hello vue.py</div>"
App("#app")
```

vue-cli deploy flask

here is the server results:
* Serving Flask app "vuecli.provider.flask" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /vuepy.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /vue.js HTTP/1.1" 200 -  
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /loading.gif HTTP/1.1" 200 -
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /__entry_point__.py?1637231063646 HTTP/1.1" 200 -
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /app.py?v=1637231063662 HTTP/1.1" 404 -
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /app/__init__.py?v=1637231063668 HTTP/1.1" 404 -
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /Lib/site-packages/app.py?v=1637231063680 HTTP/1.1" 404 -
127.0.0.1 - - [18/Nov/2021 11:24:23] "GET /Lib/site-packages/app/__init__.py?v=1637231063687 HTTP/1.1" 404 -

Loading widget forever running

Note : I have npm with vuejs3 already installed (not in this directory) can it causes problems ?

**Comment by stefanhoelzl** [comment] 2021-11-19 12:42
An already installed npm should not have any effect.

What browser and version are you using?
Can you open the developer tools of your browser and check if there are any errors/warnings?

**Comment by aaronchn** [comment] 2022-03-12 13:57
OS：windows

 pip list
Package      Version
brython      3.8.9
click        7.1.2
Flask        1.1.4
itsdangerous 1.1.0
Jinja2       2.11.3
MarkupSafe   2.0.1 
pip          22.0.4
PyYAML       5.4.1
setuptools   39.0.1
vuepy        0.3.0
Werkzeug     1.0.1

MarkupSafe must be downgrade to run > vue-cli

See [here](https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/) 
![1](https://user-images.githubusercontent.com/6897149/158020833-8bbdea15-1a03-4573-92ff-1796821139d4.png)
![2](https://user-images.githubusercontent.com/6897149/158020838-57eb1cc7-3365-4e94-965f-a63ec722cdb9.png)
![3](https://user-images.githubusercontent.com/6897149/158020851-8957e187-8e30-4ab9-9d27-221613216572.png)

**Comment by aaronchn** [comment] 2022-03-20 04:32
Finally, the 'First Application' shown in the project documentation looks like it's ready to run.

Dev environment：
  OS: linux
  Browser: Microsoft Edge Version 99.0.1150.38 (64-bit)
  Dependencies：
![Screenshot_2022-03-20_12-29-13](https://user-images.githubusercontent.com/6897149/159148228-066afe16-9654-4ca3-9d42-2c85be950ad8.png)

Hi @stefanhoelzl 
Now there are two confusions.

1：I still see some errors in the developer tools of the browser, do these errors need attention? (I'm concerned that these errors may signal that the project is not in a state to be used out of the box)
![Screenshot_2022-03-20_11-12-05](https://user-images.githubusercontent.com/6897149/159148249-3ff84951-6db4-4873-bc91-4bf790da2e86.png)

2：In the demo that comes with the project, flask is listening at 127.0.0.1:5000, I would like to listen at another address and port, how should I do that? (For example, I can bind my local lan address so that mobile phone in the same lan can access the web)

By the way, this project is very valuable for users who are familiar with python and want to do small scale web development, this project also shows the value of Brython. At the same time, the 300+ commits have laid the foundation for a project that is expected to grow robustly and should not be abandoned by the author or anyone capable of submitting a PR.

Thank you！

**Comment by stefanhoelzl** [comment] 2022-03-21 23:43
Hi @aaronchn,

Thanks for digging into the `MarkupSafe` x `Flask` issue.

Please check out the current master branch
```bash
$ pip install "git+https://github.com/stefanhoelzl/vue.py@master#egg=vuepy[flask]"
```

The dependency versions are upgraded, so `flask~=2` is also allowed. As stated in the [link](https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/) you provided, this should also fix the launch issue.

> 2：In the demo that comes with the project, flask is listening at 127.0.0.1:5000, I would like to listen at another address and port, how should I do that? (For example, I wish to bind flask to local lan address so that mobile phone in the same lan can access the web)

this is also addressed with the latest changes in master. Checkout the [documentation](https://github.com/stefanhoelzl/vue.py/blob/master/docs/docs/management/cli.md), it describes how to set [Flask Builtin Configuration Values](https://flask.palletsprojects.com/en/2.0.x/config/#builtin-configuration-values) from `vuepy.yml`. The value `SERVER_NAME` allows to change the listen address and port.

> 1：I still see some errors in the developer tools, do these errors need attention? (I'm concerned that these errors may signal that the current release is not in a state to be used out of the box)

Unfortunately this can't be fixed by `vuepy`, it is caused by brython and how the import mechanism im python works.
The python import mechanism iterates through `sys.path` and for each entry it tries to find the module to import there.
But with Brython for each entry where it does not find the module you see such an `404` error, because it tries to load the file but cannot find it.

**Comment by aaronchn** [comment] 2022-03-22 14:24
Hi @stefanhoelzl 
Thank you so much for your response and update!

I followed your guide and tried it with master, but it looks like there is a little problem. I hope the cause of this problem is not caused by pipenv's environment.

![Screenshot_2022-03-22_22-14-56](https://user-images.githubusercontent.com/6897149/159504025-45b3d304-60cc-4346-ae87-da464ae43fdd.png)
![Screenshot_2022-03-22_22-17-00](https://user-images.githubusercontent.com/6897149/159504061-b3e75b3f-04c5-47b3-a2df-39c3b62d854e.png)

**Comment by stefanhoelzl** [comment] 2022-03-23 10:25
In the meantime I made some changes to the build/CI system.

this works now
```bash
$ pip install "git+https://github.com/stefanhoelzl/vue.py@master#egg=vuepy[flask]"
```

you can also download a wheel built from current master here
https://github.com/stefanhoelzl/vue.py/releases

**Comment by aaronchn** [comment] 2022-03-23 13:23
Hi  @stefanhoelzl 

Thank you so much for your update! 

**1:** Successfully installed master to the virtual environment with
`$ pipenv install "git+https://github.com/stefanhoelzl/vue.py@master#egg=vuepy[flask]"`
btw, the "Installing dependencies from Pipfile.lock" step takes a long time, about 5 minutes.

![0](https://user-images.githubusercontent.com/6897149/159708760-f4a6028d-9ed2-48d0-b37b-f64faac25ebc.png)

**2:** The SERVER_NAME configuration in vuepy.yml is valid and I can specify the flask binding settings with this option. Now, I can access the service on my phone on the same lan.
btw, no difference in response to vuepy between pc browser and mobile browser is found for now.


**3:** Accessing 'First Application' on a pc browser still results in some 404, and although I don't quite understand your previous explanation, I guess this should not be a significant risk for my further attempts at this project.

![3](https://user-images.githubusercontent.com/6897149/159709011-012f9443-87e6-4ba5-9c8d-bc500cea9b34.png)

**Comment by stefanhoelzl** [comment] 2022-03-23 13:34
Great! As far as I understand all your issues are resolved? 
I will close this ticket, feel free to re-open or create a new issue if other problems occur.

Regarding the 404 error, a bit more explanation:
Lets say this is our project structure:
```
package
|-__init__.py
|-sub.py
```
when you do a `import package` with brython, it cannot know in advance if `package` is a directory or a file, so it tries to access `package.py` if it gets a 404, so it next tries to access `package/__init__.py` which succeeds.

Lets look at the `vuepy` project structure
```
vue
|-bridge
   |- <multiple .py files>
|-decorators
   |- <multiple .py files>
```
You get the 404 errors when brython tries to load a module which is a directory (`vue`, `bridge`, `decorators`)

So nothing to worry about the 404, it is part of how brython works.

**Comment by aaronchn** [comment] 2022-03-23 14:06
Hi @stefanhoelzl 

Sorry to interrupt again

When I write a fixed address of 10.0.0.155 for a lan to vuepy.yml, Flask works fine.

When I try to use 0.0.0.0 as the address to wait for a request, flask seems to be able to interpret 0.0.0.0 as the current address 10.0.0.155 for that pc. However, an error is encountered when trying to request it.

![Screenshot_2022-03-23_22-00-13](https://user-images.githubusercontent.com/6897149/159718026-240a8e98-02f0-4213-b752-079749b99ad6.png)
![Screenshot_2022-03-23_21-59-52](https://user-images.githubusercontent.com/6897149/159718059-162d0999-d4b7-42e4-86a6-ee95a66360f4.png)

**Comment by stefanhoelzl** [comment] 2022-03-23 18:51
my bad, `SERVER_NAME` is the wrong setting.

re-install `vuepy` from GitHub, to get the latest changes 
```bash
pip uninstall vuepy
pip install "git+https://github.com/stefanhoelzl/vue.py@master#egg=vuepy[flask]"
```

and try this `vuepy.yml`
```yaml
provider:
  flask:
    HOST: "0.0.0.0"
    PORT: 5001
```

**Comment by aaronchn** [comment] 2022-03-23 22:28
After configuring vuepy.yml in the new format and reinstalling master, the results are as follows.

![Screenshot_2022-03-24_06-21-39](https://user-images.githubusercontent.com/6897149/159806196-6d53101b-36c8-4977-958d-41e3faec1895.png)

I think this is probably normal and does not need to be noticed.


So far all my problems have been solved perfectly.

Thx.
Have a good day!

**Closed** 2022-03-23 22:30 UTC

**Comment by bobwatcherx** [comment] 2023-04-23 03:12
i get errror when running project
root@mino-HP-Convertible-x360-11-ab1XX:/home/mino/belajar/vuepy#  vue-cli deploy flask
Traceback (most recent call last):
  File "/usr/local/bin/vue-cli", line 5, in <module>
    from vuecli.cli import main
  File "/usr/local/lib/python3.10/dist-packages/vuecli/cli.py", line 6, in <module>
    from vuecli.provider import RegisteredProvider
  File "/usr/local/lib/python3.10/dist-packages/vuecli/provider/__init__.py", line 11, in <module>
    RegisteredProvider = {
  File "/usr/local/lib/python3.10/dist-packages/vuecli/provider/__init__.py", line 12, in <dictcomp>
    entry_point.name: _load(entry_point)
  File "/usr/local/lib/python3.10/dist-packages/vuecli/provider/__init__.py", line 6, in _load
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.10/dist-packages/vuecli/provider/flask.py", line 4, in <module>
    from flask import Flask as FlaskApp, send_file, abort
  File "/usr/local/lib/python3.10/dist-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/local/lib/python3.10/dist-packages/flask/json/__init__.py", line 6, in <module>
    from jinja2.utils import htmlsafe_json_dumps as _jinja_htmlsafe_dumps
  File "/usr/local/lib/python3.10/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.10/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.10/dist-packages/markupsafe/__init__.py)

my code 
from vue import *

class App(VueComponent):
    template = "<div>Hello vue.py</div>"
App("#app")
